from .ColorPickerItem import ColorPickerItem1D
from .ColorGradientWidget import ColorGradientMainWidget as ColorGradientMainWidget
from .ColorDisplayWidget import ClockDisplayWidget

from .ColorInputWidget import ColorInputWidget as ColorInputWidget
